# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4fcac1bbe208e04dad11f6f8ccb08f15d6f7975f5d55259173dd055a8badb3c8664595f56f9fabdcfdfa39ab6a3e1a49fdab0a6771f11c35d2c00cb71d5cfc

test:
  secret_key_base: c5c4bed6bc0d49a025f9bd5b961e7193d4eada697991c8dbb57388b8769c8a831721149cfb5581d42a2dcfd72f6905d8879715a458329aac5d26fb4f72f93d93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
